name: Publicação via FTP (ANVY)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  publicar-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ANVY_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /checkplanilha.anvy.com.br
